feat(#11): include input checkbox for task lists
sivukhin/godjot pull request #12
Opened 2024-12-21 02:40 UTC by KyleKing

This is the first go project I've actually worked on, so any guidance would be appreciated! I've been running `make test lint` locally, but the Emoji test (35) fails and I think my changes are generally the right direction, but I'm not sure what to do to finish the change

2024-12-21 13:37 UTC, sivukhin commented
Hi @KyleKing!

Yes, emoji test were broken in the master as tests download fresh HTML from djot syntax spec page (https://htmlpreview.github.io/?https://github.com/jgm/djot/blob/master/doc/syntax.html) which recently changed `symbols` example. I fixed them - so if you will update your fork - this test must be good for now.

Regarding the approach - what do you think if input checkbox will be supported only in the rendering layer? I see drawback in the current approach as new AST for checkboxed-list can make maintenance harder because on one hand - this is new AST node but on the other hand - it must behave just as regular list and the only difference is in the presentation layer.

I would suggest to add this feature only in the rendering layer by extending logic of `DefaultConversionRegistry` for `ListItemNode`. But internally all lists will be presented as `ListItemNode`.

The development flow is simple and you did everything right: `make line test` is enough and I didn't setup any more automatic checks. One useful thing can be to run `FuzzDjotE2E` / `FuzzDjotTokenizer` tests in fuzzing mode (pass `-fuzz` argument to the `go test` command) if you touch parser internals - because its proven (by myself) that mistakes are easy to made in this code :) But for "front-end" rendering part it's not that useful as conversions in this part of the code is pretty straightforward.

2025-01-02 21:00 UTC, KyleKing reviewed
Ready for review again! Feel free to make changes directly if easier than providing feedback

2025-01-05 11:50 UTC, sivukhin requested changes
Nice! I like current approach but seems like current code has a bug if item list has some non-trivial internal content

2025-01-05 11:50 UTC, sivukhin commented on djot_parser/djot_html.go
> +				if len(s.Node.Children) > 1 {
It seems to me that you should just print all children here and do not trim any because there can be more content in the subtree (I think you can get extra new line because of this - but you can just do not emit it manually and let `n(s.Node.Children)` to handle that automatically)

2025-01-05 11:50 UTC, sivukhin commented on djot_parser/examples/todo-list.html
> -<li class="unchecked">
Let's add one more test where checkbox item list will have some non-paragraph content inside like:
```
- [ ] unchecked

 * 1
 * 2
 * 3
- [x] checked
- [ ] finish
```

2025-01-06 01:00 UTC, KyleKing reviewed
Thanks for the review! I can finish resolving the extra newline in the test tomorrow or it could probably be merged as-is (I run the generated HTML through a minifier anyway)

2025-01-06 01:00 UTC, KyleKing commented on djot_parser/examples/todo-list.html
> +
I'll figure out how to output HTML without this extra newline tomorrow, which may be the last change necessary

2025-01-06 01:00 UTC, KyleKing commented on djot_parser/examples/todo-list.html
> -<li class="unchecked">
One other change to consider are nested paragraphs like the djot.js test: https://github.com/dcampbell24/djot.js/blob/22470195eb0dc1fc942b34b7c8d95b23597c094a/test/task_lists.test

I added the test from `djot.js` verbatim. While the `*`-based lists are currently failing, I can address that in a future PR (https://htmlpreview.github.io/?https://github.com/jgm/djot/blob/master/doc/syntax.html#list-item)

2025-01-08 01:34 UTC, KyleKing commented on djot_parser/examples/todo-list.html
> +
I took another look at this, but I'm at a loss for where the bug is. It is definitely from the end of the file/list, but the changes I've tried have had side-effects. Any advice on what might be wrong?

2025-01-11 21:34 UTC, sivukhin approved these changes
I tweaked djot markup in todo-list test a bit because there are nuances related to the EOF handling in `godjot`

I will merge this branch. @KyleKing - thanks one more time for contribution! Sorry that it took longer than it actually needed to be!

2025-01-11 21:35 UTC, merged